version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: monorepo-postgres
    environment:
      POSTGRES_DB: monorepo_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./logs:/var/log/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Backend service for development
  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
      target: development
    container_name: monorepo-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=monorepo_dev
      - PORT=3001
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/packages/backend/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    command: npm run dev --workspace=@monorepo/backend

volumes:
  postgres_data: